---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: dev
  labels:
    app: sample-app
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: dev
  labels:
    app: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: tomcat-app
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 8080
        resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "400m"
